[package]
name = "mcping"
version = "1.0.0"
edition = "2021"


[dependencies]
axum = { version = "0.5", features = ["headers"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"]}
mcping = { path = "mcping", features = ["tokio-runtime"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"