version: "3.7"
services:
  mcpingme:
    image: ghcr.io/randomairborne/mcping
    restart: always
    networks:
      - proxy
    deploy:
      labels:
        traefik.enable: true
        traefik.http.routers.dswrap.rule: Host(`${HOST}`)
        traefik.http.routers.dswrap.entrypoints: https
        traefik.http.routers.dswrap.tls.certresolver: letsencrypt
        traefik.http.services.dswrap.loadbalancer.server.port: 8080

networks:
  proxy:
    external: true