version: "3.7"
services:
  mcping:
    image: ghcr.io/randomairborne/mcping
    restart: always
    networks:
      - proxy
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.mcping.rule: Host(`${HOST}`)
        traefik.http.routers.mcping.entrypoints: https
        traefik.http.routers.mcping.tls.certresolver: letsencrypt
        traefik.http.services.mcping.loadbalancer.server.port: 8080
        traefik.http.routers.mcping-http.rule: Host(`${HOST}`)
        traefik.http.routers.mcping-http.entrypoints: http
        traefik.http.services.mcping-http.loadbalancer.server.port: 8080
        traefik.http.middlewares.mcping-https-redirect.redirectscheme.scheme: https
        traefik.http.middlewares.mcping-https-redirect.redirectscheme.permanent: "true"
        traefik.http.routers.mcping-http.middlewares: mcping-https-redirect

networks:
  proxy:
    external: true